### ISSUE TITLE
A question about results

### ISSUE THREAD

**Issue by kornelhowil** [SunYangtian/Splatter_A_Video#2]
Hi, great work!
I have a question regarding the resolution of the DAVIS dataset used in the quantitative comparison in Table 1. I couldn’t find any mention of the specific resolution in the paper. Could you clarify which resolution was used?
Thanks!

**Comment by SunYangtian** [comment]
We use the DAVIS dataset 480p, containing images with resolution 480 x 854.  We have reported more thorough results in [the latest paper](https://github.com/SunYangtian/Splatter_A_Video/blob/main/paper/paper.pdf)

**Comment by kornelhowil** [comment]
Thanks!
